### ISSUE TITLE
求该课程对应的视频资源

### ISSUE THREAD

**Issue by ruqing00** [YingnanHan/Introduction-and-Practice-of-PyTorch-Deep-Learning#1]
如果有《Pytorch深度学习入门与实战》课程的视频资源，求佬分享一下

**Comment by YingnanHan** [comment]
这个资源是我在官网上学习对应课程自己写的代码，当时(大约两年前)是在https://study.163.com/上购买的课程，很抱歉课程并没有保存下来。此外希望您支持正版。

**Comment by ruqing00** [comment]
> 

好的，感谢感谢
